# Generated by Django 4.0.2 on 2022-02-22 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('audioID', models.AutoField(primary_key=True, serialize=False)),
                ('audioLength', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('interviewerID', models.AutoField(primary_key=True, serialize=False)),
                ('interviewerFirstName', models.CharField(max_length=255)),
                ('interviewerLastName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Veteran',
            fields=[
                ('veteranID', models.AutoField(primary_key=True, serialize=False)),
                ('veteranFirstName', models.CharField(max_length=255)),
                ('veteranLastName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interviewID', models.AutoField(primary_key=True, serialize=False)),
                ('interviewDate', models.DateField()),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewers', to='API.audio')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewers', to='API.interviewer')),
                ('veteran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewers', to='API.veteran')),
            ],
        ),
    ]
