# Generated by Django 4.0.2 on 2022-02-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_audio_audiolength'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audioTitle',
            field=models.CharField(default='No Title', max_length=255),
        ),
    ]
